###############################################################
# Program:
#     Week 01, Vector
#     Brother Helfrich, CS235
# Author:
#     Justin Waite
# Summary:
#     Mimics the implementation of std::vector
# Time:
#     Apprx. 2 hours
###############################################################

##############################################################
# The main rule
##############################################################
a.out: vector.h week01.o
	g++ -o a.out week01.o
	tar -cf week01.tar vector.h week01.cpp makefile

##############################################################
# The individual components
#      week01.o     : the driver program
##############################################################
week01.o: vector.h week01.cpp
	g++ -c week01.cpp
